# This file is for local development
FROM oven/bun:1-slim

RUN apt-get update && \
    apt-get install -y curl bash unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://encore.dev/install.sh | bash

# Add Encore to the system PATH
ENV PATH="/root/.encore/bin:$PATH"

WORKDIR /app