name: Deploy Todo API to GCP Swarm

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'sst.config.ts'
            - '.sst/**'
            - 'README.md'
            - '.gitignore'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download Encore CLI script
              uses: sozo-design/curl@v1.0.2
              with:
                  args: --output install.sh -L https://encore.dev/install.sh

            - name: Install Encore CLI
              run: bash install.sh

            - name: Authenticate with Encore
              run: /home/runner/.encore/bin/encore auth login --auth-key=${{ secrets.ENCORE_AUTH_KEY }}

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  workload_identity_provider: 'projects/985227244631/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-provider'
                  service_account: todo-github-deployer@voltarocks-42-sandbox.iam.gserviceaccount.com

            - name: Configure Docker for Artifact Registry
              run: |
                  gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

            - name: Build and Push Docker image
              run: |
                  /home/runner/.encore/bin/encore build docker todo-app
                  docker tag todo-app asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/todo-repo/todo-app:latest
                  docker push asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/todo-repo/todo-app:latest

            - name: Build and Push Postgres WAL-G image
              run: |
                  docker build -t asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/todo-repo/postgres-walg:latest ./postgres
                  docker push asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/todo-repo/postgres-walg:latest

            - name: Discover VM name
              run: |
                  # Search for the VM with the tag 'todo-iac-vm' and extract only its name
                  DYNAMIC_NAME=$(gcloud compute instances list \
                    --project=voltarocks-42-sandbox \
                    --filter="tags.items=todo-iac-vm" \
                    --format="value(name)" \
                    --limit=1)

                  echo "Found VM: $DYNAMIC_NAME"
                  # Save it to the GitHub Environment so the next steps can use it
                  echo "VM_NAME=$DYNAMIC_NAME" >> $GITHUB_ENV

            - name: Wait for Docker to be ready
              run: |
                  echo "Waiting for startup script to finish..."
                  # This loop checks if docker is installed every 10 seconds, up to 10 times
                  for i in {1..10}; do
                    if gcloud compute ssh $VM_NAME --zone=asia-southeast1-a --tunnel-through-iap --command "which docker" > /dev/null 2>&1; then
                      echo "Docker is ready!"
                      exit 0
                    fi
                    echo "Docker not ready yet... sleeping 10s"
                    sleep 10
                  done
                  echo "Timed out waiting for Docker"
                  exit 1

            - name: Create DATABASE_URL secret
              run: |
                  echo "${{ secrets.DATABASE_URL }}" | gcloud compute ssh $VM_NAME \
                  --zone=asia-southeast1-a \
                  --project=voltarocks-42-sandbox \
                  --tunnel-through-iap \
                  --command="sudo docker secret inspect db_url >/dev/null 2>&1 || echo "${{ secrets.DATABASE_URL }}" | sudo docker secret create db_url -"

            - name: Deploy to Compute Engine via gcloud
              run: |
                  gcloud compute scp docker-compose.prod.yml prometheus.yml $VM_NAME:~ \
                  --zone=asia-southeast1-a \
                  --project=voltarocks-42-sandbox \
                  --tunnel-through-iap

                  gcloud compute ssh $VM_NAME \
                  --zone=asia-southeast1-a \
                  --project=voltarocks-42-sandbox \
                  --tunnel-through-iap \
                  --command "sudo GRAFANA_PASSWORD='${{ secrets.GRAFANA_PASSWORD }}' \
                       BACKUP_BUCKET='${{ secrets.BACKUP_BUCKET }}' \
                       docker stack deploy --with-registry-auth -c docker-compose.prod.yml todo-app"
